# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20171009_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=38),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_cost',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
