# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_auto_20171009_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField(verbose_name='START DATE OF WEEK')),
                ('Task', models.CharField(max_length=100, verbose_name='TASK NAME')),
                ('contractor', models.ManyToManyField(to='Projects.Contractor', verbose_name='CONTRACTOR')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank='True', decimal_places=2, max_digits=38, null='True', verbose_name='BUDGET PER MONTH'),
        ),
        migrations.AddField(
            model_name='task',
            name='projectname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.Project', verbose_name='PROJECTNAME'),
        ),
    ]
