# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_remove_userprofile_dateofjoin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
